In [39]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [40]:
df = pd.read_csv('train.txt', sep=';', header=None, names=['text', 'emotion'])

In [41]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [42]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [43]:
df.shape

(16000, 2)

In [44]:
df['emotion'].value_counts()

emotion
joy         5362
sadness     4666
anger       2159
fear        1937
love        1304
surprise     572
Name: count, dtype: int64

In [45]:
unique_emotions = df['emotion'].unique()
emotions_numbers = {}
i = 0
for emotion in unique_emotions:
    emotions_numbers[emotion] = i
    i += 1
df['emotion'] = df['emotion'].map(emotions_numbers)

In [46]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

In [47]:
df['text'] = df['text'].str.lower()

In [48]:
import string
def remove_punctuation(text):
    return text.translate(str.maketrans('', '', string.punctuation))

df['text'] = df['text'].apply(remove_punctuation)

In [49]:
def remove_numbers(text):
    return ''.join([i for i in text if not i.isdigit()])

df['text'] = df['text'].apply(remove_numbers)

In [50]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

In [51]:
def remove_urls(text):
    return ' '.join([word for word in text.split() if not word.startswith('http')])

df['text'] = df['text'].apply(remove_urls)

In [52]:
def remove_emojis(text):
    new = ""
    for character in text:
        if character.isascii():
            new += character
    return new

df['text'] = df['text'].apply(remove_emojis)

In [53]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.downloader import download

In [54]:
download('punkt')
download('stopwords')
download('punkt_tab')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Rishi\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Rishi\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Rishi\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [55]:
stop_words = set(stopwords.words('english'))
len(stop_words)

198

In [56]:
def remove_stopwords(text):
    tokens = word_tokenize(text)
    filtered_tokens = [word for word in tokens if word not in stop_words]
    return ' '.join(filtered_tokens)

try:
    df['text'] = df['text'].apply(remove_stopwords)
except Exception as e:
    print(f"Error occurred: {e}")

In [57]:
df.head()

                                                text  emotion
0                              didnt feel humiliated        0
1  go feeling hopeless damned hopeful around some...        0
2          im grabbing minute post feel greedy wrong        1
3  ever feeling nostalgic fireplace know still pr...        2
4                                    feeling grouchy        1

In [58]:
from sklearn.feature_extraction.text import CountVectorizer

In [74]:
vectorizer = CountVectorizer(ngram_range=(2, 2))
vectorizer_1gram = CountVectorizer(ngram_range=(1, 1), max_features=1000)
vectorizer_3gram = CountVectorizer(ngram_range=(3, 3), max_features=1000)
vectorizer_1to3gram = CountVectorizer(ngram_range=(1, 3), max_features=1000) # 1 to 3 grams all together

In [75]:
X_bag_of_words = vectorizer.fit_transform(df['text'])

In [76]:
print(f"Shape of the bag-of-words matrix: {X_bag_of_words.shape}")
print(f"Number of unique words (features): {len(vectorizer.get_feature_names_out())}")
vectorizer.get_feature_names_out()[56:77]  # Display the first 10 feature names

Shape of the bag-of-words matrix: (16000, 95337)
Number of unique words (features): 95337

array(['ability money', 'ability mourn', 'ability pull',
       'ability quickly', 'ability rhyme', 'ability segregate',
       'ability simply', 'ability step', 'ability think',
       'ability thrilled', 'ability understand', 'abit dull',
       'abit grouchy', 'abit hopeless', 'abit uncertain', 'able acquire',
       'able actually', 'able apart', 'able attend', 'able better',
       'able boost'], dtype=object)

In [77]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [78]:
tfidf_vectorizer = TfidfVectorizer()

In [81]:
X_tfidf = tfidf_vectorizer.fit_transform(df['text'])

In [84]:
print(f"Shape of the bag-of-words matrix: {X_bag_of_words.shape}")
print(f"Number of unique words (features): {len(vectorizer.get_feature_names_out())}")
print(f"Shape of the TF-IDF matrix: {X_tfidf.shape}")
print("First 10 feature names:", tfidf_vectorizer.get_feature_names_out()[56:77])
print("Matrix (first 10 rows):", X_tfidf[0:10])

Shape of the bag-of-words matrix: (16000, 95337)
Number of unique words (features): 95337
Shape of the TF-IDF matrix: (16000, 15042)
First 10 feature names: ['academic' 'academics' 'academy' 'acause' 'accelerated' 'accent'
 'accentuating' 'accept' 'acceptable' 'acceptance' 'acceptances'
 'accepted' 'accepting' 'accepts' 'access' 'accessaries' 'accessibility'
 'accessories' 'accessory' 'accident' 'accidentally']
Matrix (first 10 rows): <Compressed Sparse Row sparse matrix of dtype 'float64'
	with 67 stored elements and shape (10, 15042)>
  Coords	Values
  (0, 3585)	0.5951235084078971
  (0, 4886)	0.16379156905484632
  (0, 6368)	0.7867657412767967
  (1, 5633)	0.2472161491010906
  (1, 4890)	0.11315242650138915
  (1, 6282)	0.3391180698816026
  (1, 3175)	0.4728128292698571
  (1, 6280)	0.34329019535147487
  (1, 690)	0.25735593796737716
  (1, 12271)	0.2703838370526541
  (1, 1926)	0.41218505617295464
  (1, 916)	0.40055397920248415
  (2, 4886)	0.08634244868782456
  (2, 6491)	0.18407021588693162
  (2, 5688)	0.5446643643162221
  (2, 8369)	0.4597172250718977
  (2, 10046)	0.36532428583649834
  (2, 5749)	0.4005805340793545
  (2, 14897)	0.395900672251109
  (3, 4890)	0.129430299030204
  (3, 4525)	0.3171370613439837
  (3, 8967)	0.4012071889690798
  (3, 5015)	0.5541349981325937
  (3, 7348)	0.2370572214656242
  (3, 12618)	0.2567977930926231
  :	:
  (6, 4777)	0.3254224337372334
  (6, 755)	0.2926947604271603
  (6, 7825)	0.1988432050515877
  (6, 4823)	0.3100814292189363
  (6, 408)	0.18434489845397767
  (6, 7654)	0.10558291768563384
  (6, 5402)	0.24445180512547848
  (7, 4886)	0.08432732053425672
  (7, 2649)	0.38492603360042105
  (7, 7629)	0.26354888314493535
  (7, 13216)	0.4812449234582412
  (7, 6996)	0.4113680851226073
  (7, 14950)	0.33112426367408165
  (7, 9146)	0.35266909210131997
  (7, 7990)	0.3747314952498339
  (8, 4886)	0.052665863113911734
  (8, 9719)	0.7465767621685409
  (8, 14958)	0.21191596680907032
  (8, 9647)	0.35813353139409326
  (8, 14603)	0.18980840745718705
  (8, 7931)	0.18779482589720328
  (8, 6347)	0.2733381757007819
  (8, 10283)	0.3473809944201784
  (9, 4886)	0.20495173480695994
  (9, 11220)	0.9787720809256962

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df['text'], df['emotion'], test_size=0.2, random_state=42)

In [ ]:
df.shape

(16000, 2)

In [ ]:
count_vectorizer = CountVectorizer() # bag of words
tfidf_vectorizer = TfidfVectorizer()

In [89]:
x_train_count = count_vectorizer.fit_transform(X_train)

In [92]:

x_test_count = count_vectorizer.transform(X_test)

In [93]:
from sklearn.naive_bayes import MultinomialNB

In [94]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [95]:
nb_model = MultinomialNB()

In [96]:
nb_model.fit(x_train_count, y_train)

MultinomialNB()

In [97]:
nb_model.score(x_test_count, y_test)

0.7684375

In [98]:
y_pred = nb_model.predict(x_test_count)

In [100]:
accuracy = accuracy_score(y_test, y_pred)
print("bag of words accuracy:", accuracy)

bag of words accuracy: 0.7684375

In [102]:
x_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
x_test_tfidf = tfidf_vectorizer.transform(X_test)

In [103]:
nb2_model = MultinomialNB()
nb2_model.fit(x_train_tfidf, y_train)

MultinomialNB()

In [104]:
y_pred = nb2_model.predict(x_test_tfidf)

In [105]:
accuracy = accuracy_score(y_test, y_pred)
print("tfidf accuracy:", accuracy)

tfidf accuracy: 0.66125

In [106]:
from sklearn.linear_model import LogisticRegression

In [107]:
lr = LogisticRegression(max_iter=1000)
lr.fit(x_train_tfidf, y_train)

LogisticRegression(max_iter=1000)

In [108]:
y_pred = lr.predict(x_test_tfidf)

In [109]:
accuracy = accuracy_score(y_test, y_pred)
print("tfidf accuracy:", accuracy)

tfidf accuracy: 0.861875